### ISSUE TITLE
Fehler: Konnte Informationen aus E-Mails nicht extrahieren

### ISSUE THREAD

**Issue by Jokerx3** [farOverNinethousand/AralActivator#1]
Hier der aktuelle E-Mail Inhalt:

 	Aral Header Logo	Aral SuperCard - Vielen Dank für Ihre Bestellung	 
Sehr geehrte(r) Kunde(in),
hiermit bestätigen wir Ihnen die Bestellung mit der Bestellnummer 123456789 über folgende Produkte:

Wert	Anzahl	Gesamtkosten
Aral SuperCard Einkaufen & Tanken 30 €	30,00 €	1	30,00 €
Gutschrift	 	1	-30,00 €
Bearbeitungsgebühren*	0,95 €
Gutschrift	-0,95 €
Versandkosten	3,00 €
Gutschrift	-3,00 €
19% MwSt.**	0,00 €
Summe inkl. MwSt.	0,00 €
+ 5 EUR Groupon-Aktion!

* Fertigung / Material / Bearbeitung
** Außer Kartennennwert

Rechnungsadresse
Max Mustermann
Musterstr. 1
12345 Musterhausen

Lieferadresse
Max Mustermann
Musterstr. 1
12345 Musterhausen

Bestellinformationen:
Groupon XMAS19: 1234-5678-1212 

Mit freundlichen Grüßen,
Ihr Aral SuperCard Team

 	 	 	 	 
 	 	Impressum    Datenschutz    Kontaktieren Sie uns	 	 
 	 	 	 	 
 	Copyright © 2019 Aral	Aral - ein Unternehmen der BP Group BP Footer Logo

**Comment by farOverNinethousand** [comment]
Wie gesagt ich werde das Errorhandling trotzdem verbessern, aber ein Bug in dem Sinne ist es nicht :)

Grüße
